package org.tmjee.miniwiki.core.service;

/**
 * @author tmjee
 * @version $Date$ $Id$
 */
public enum PriviledgePageLevel {

    // Anonymous
    PAGE_LEVEL_VIEW_PAGE_ANONYMOUS,
    PAGE_LEVEL_EDIT_PAGE_ANONYMOUS,
    PAGE_LEVEL_DELETE_PAGE_ANONYMOUS,
    PAGE_LEVEL_COMMNET_PAGE_ANONYMOUS,

    // Registered
    PAGE_LEVEL_VIEW_PAGE_REGISTERED,
    PAGE_LEVEL_EDIT_PAGE_REGISTERED,
    PAGE_LEVEL_DELETE_PAGE_REGISTERED,
    PAGE_LEVEL_COMMNET_PAGE_REGISTERED,

    // Group
    PAGE_LEVEL_VIEW_PAGE_GROUP,
    PAGE_LEVEL_EDIT_PAGE_GROUP,
    PAGE_LEVEL_DELETE_PAGE_GROUP,
    PAGE_LEVEL_COMMNET_PAGE_GROUP
}
