package org.tmjee.miniwiki.core.service;

/**
 * @author tmjee
 * @version $Date$ $Id$
 */
public enum PriviledgeSpaceLevel {

    // Anonymous
    SPACE_LEVEL_VIEW_SPACE_ANONYMOUS,
    SPACE_LEVEL_EDIT_SPACE_ANONYMOUS,
    SPACE_LEVEL_DELETE_SPACE_ANONYMOUS,
    SPACE_LEVEL_VIEW_PAGE_ANONYMOUS,
    SPACE_LEVEL_CREATE_PAGE_ANONYMOUS,
    SPACE_LEVEL_EDIT_PAGE_ANONYMOUS,
    SPACE_LEVEL_DELETE_PAGE_ANONYMOUS,
    SPACE_LEVEL_COMMENT_PAGE_ANONYMOUS,


    // Registered
    SPACE_LEVEL_VIEW_SPACE_REGISTERED,
    SPACE_LEVEL_EDIT_SPACE_REGISTERED,
    SPACE_LEVEL_DELETE_SPACE_REGISTERED,
    SPACE_LEVEL_VIEW_PAGE_REGISTERED,
    SPACE_LEVEL_CREATE_PAGE_REGISTERED,
    SPACE_LEVEL_EDIT_PAGE_REGISTERED,
    SPACE_LEVEL_DELETE_PAGE_REGISTERED,
    SPACE_LEVEL_COMMENT_PAGE_REGISTERED,


    // Group
    SPACE_LEVEL_VIEW_SPACE_GROUP,
    SPACE_LEVEL_EDIT_SPACE_GROUP,
    SPACE_LEVEL_DELETE_SPACE_GROUP,
    SPACE_LEVEL_VIEW_PAGE_GROUP,
    SPACE_LEVEL_CREATE_PAGE_GROUP,
    SPACE_LEVEL_EDIT_PAGE_GROUP,
    SPACE_LEVEL_DELETE_PAGE_GROUP,
    SPACE_LEVEL_COMMENT_PAGE_GROUP
}
