package org.tmjee.miniwiki.core.service;

/**
 * @author tmjee
 * @version $Date$ $Id$
 */
public enum PriviledgeWikiLevel {

    // Anonymous
    WIKI_LEVEL_ADMINISTRATION_ANONYMOUS,
    WIKI_LEVEL_REGISTRATION_ANONYMOUS,
    WIKI_LEVEL_VIEW_WIKI_ANONYMOUS,
    WIKI_LEVEL_EDIT_WIKI_ANONYMOUS,
    WIKI_LEVEL_DELETE_WIKI_ANONYMOUS,
    WIKI_LEVEL_CREATE_SPACE_ANONYMOUS,
    WIKI_LEVEL_DELETE_SPACE_ANONYMOUS,
    WIKI_LEVEL_VIEW_SPACE_ANONYMOUS,
    WIKI_LEVEL_EDIT_SPACE_ANONYMOUS,
    



    // Registered
    WIKI_LEVEL_ADMINISTRATION_REGISTERED,
    WIKI_LEVEL_REGISTRATION_REGISTERED,
    WIKI_LEVEL_VIEW_WIKI_REGISTERED,
    WIKI_LEVEL_EDIT_WIKI_REGISTERED,
    WIKI_LEVEL_DELETE_WIKI_REGISTERED,
    WIKI_LEVEL_CREATE_SPACE_REGISTERED,
    WIKI_LEVEL_DELETE_SPACE_REGISTERED,
    WIKI_LEVEL_VIEW_SPACE_REGISTERED,
    WIKI_LEVEL_EDIT_SPACE_REGISTERED,



    // Group
    WIKI_LEVEL_ADMINISTRATION_GROUP,
    WIKI_LEVEL_REGISTRATION_GROUP,
    WIKI_LEVEL_VIEW_WIKI_GROUP,
    WIKI_LEVEL_EDIT_WIKI_GROUP,
    WIKI_LEVEL_DELETE_WIKI_GROUP,
    WIKI_LEVEL_CREATE_SPACE_GROUP,
    WIKI_LEVEL_DELETE_SPACE_GROUP,
    WIKI_LEVEL_VIEW_SPACE_GROUP,
    WIKI_LEVEL_EDIT_SPACE_GROUP

}
