package org.tmjee.miniwiki.core.service;

/**
 * @author tmjee
 * @version $Date$ $Id$
 */
public enum PriviledgeGlobalLevel {

    // Anonymous
    GLOBAL_LEVEL_ADMINISTRATION_ANONYMOUS,
    GLOBAL_LEVEL_REGISTRATION_ANONYMOUS,
    GLOBAL_LEVEL_CREATE_WIKI_ANONYMOUS,
    GLOBAL_LEVEL_VIEW_WIKI_ANONYMOUS,
    GLOBAL_LEVEL_EDIT_WIKI_ANONYMOUS,
    GLOBAL_LEVEL_DELETE_WIKI_ANONYMOUS,
    GLOBAL_LEVEL_CREATE_SPACE_ANONYMOUS,
    GLOBAL_LEVEL_VIEW_SPACE_ANONYMOUS,
    GLOBAL_LEVEL_EDIT_SPACE_ANONYMOUS,
    GLOBAL_LEVEL_DELETE_SPACE_ANONYMOUS,


    // Registered
    GLOBAL_LEVEL_ADMINISTRATION_REGISTERED,
    GLOBAL_LEVEL_REGISTRATION_REGISTERED,
    GLOBAL_LEVEL_CREATE_WIKI_REGISTERED,
    GLOBAL_LEVEL_VIEW_WIKI_REGISTERED,
    GLOBAL_LEVEL_EDIT_WIKI_REGISTERED,
    GLOBAL_LEVEL_DELETE_WIKI_REGISTERED,
    GLOBAL_LEVEL_CREATE_SPACE_REGISTERED,
    GLOBAL_LEVEL_VIEW_SPACE_REGISTERED,
    GLOBAL_LEVEL_EDIT_SPACE_REGISTERED,
    GLOBAL_LEVEL_DELETE_SPACE_REGISTERED,

    
    // Group
    GLOBAL_LEVEL_ADMINISTRATION_GROUP,
    GLOBAL_LEVEL_REGISTRATION_GROUP,
    GLOBAL_LEVEL_CREATE_WIKI_GROUP,
    GLOBAL_LEVEL_VIEW_WIKI_GROUP,
    GLOBAL_LEVEL_EDIT_WIKI_GROUP,
    GLOBAL_LEVEL_DELETE_WIKI_GROUP,
    GLOBAL_LEVEL_CREATE_SPACE_GROUP,
    GLOBAL_LEVEL_VIEW_SPACE_GROUP,
    GLOBAL_LEVEL_EDIT_SPACE_GROUP,
    GLOBAL_LEVEL_DELETE_SPACE_GROUP

    
}
